version: "3.4"

services:

  esp32client.api:
    image: ${DOCKER_REGISTRY-}esp32clientapi
    build:
      context: .
      dockerfile: esp32-client/Dockerfile
    container_name: esp32client.api
    restart: always
    ports:
      - "8051:443"
      - "5051:5000"
    volumes:
      - D:/MiQ/MiQ_NT/ESP32Client/FileData:/app/FileData
    environment:
      - Settings:Subnet=192.168.1.
      - Settings:Port=80
      - Settings:ConnectionTimeOut=500
      - Settings:GetDataTimeOut=1000
      - Settings:PostFileTimeOut=1000
      - Settings:FileDataDirectory=/app/FileData/
      # - Settings:ListServer=192.168.1.203;192.168.1.202;192.168.101.84
      - Settings:ListServer={"192.168.1.201":"Machine201","192.168.1.202":"Machine202","192.168.1.203":"Machine203"}
      - Settings:NodeServerName=//h2
      - Settings:ServerNamePath=SYSTEM~1/NAME.TXT
      - Settings:NodeListEspFile=//table[@class='fixed']/tbody/tr
      - Settings:NodeServerState=//p[@id='result']
      - Settings:ConnectionString=server=mysql;database=espclient;allowuservariables=True;user id=root;password=admin1234;port=3306
  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "8040:8000"
      - "9040:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - D:/MiQ/MiQ_NT/ESP32Client/Databse:/var/lib/mysql
    command:
      - "mysqld"
      - "--binlog_expire_logs_seconds=259200"
      - "--max_connections=500"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      - UPLOAD_LIMIT=1G
      - PMA_HOST=mysql
      - PMA_PORT=3306
    restart: always
    ports:
      - "8886:80"

volumes:
  portainer_data:
