version: "3.4"

services:

  esp32client.api:
    image: ${DOCKER_REGISTRY-}esp32clientapi
    build:
      context: .
      dockerfile: esp32-client/Dockerfile
    container_name: esp32client.api
    restart: always
    ports:
      - "8051:443"
      - "5051:5000"
    volumes:
      - D:/MiQ/MiQ_NT/ESP32Client/FileData:/app/FileData
    environment:
      - Settings:Subnet=192.168.1.
      - Settings:Port=80
      - Settings:ConnectionTimeOut=500
      - Settings:GetDataTimeOut=1000
      - Settings:PostFileTimeOut=1000
      - Settings:FileDataDirectory=/app/FileData/
      # - Settings:ListServer=192.168.1.203;192.168.1.202;192.168.101.84
      - Settings:ListServer={"192.168.1.201":"Machine201","192.168.1.202":"Machine202","192.168.1.203":"Machine203"}
      - Settings:NodeServerName=//h2
      - Settings:ServerNamePath=SYSTEM~1/NAME.TXT
      - Settings:NodeListEspFile=//table[@class='fixed']/tbody/tr
      - Settings:NodeServerState=//p[@id='result']
  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "8040:8000"
      - "9040:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
